settings:
  title: 'Status Page'
  url: 'https://status.home31.pw' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 30 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: webmail.home31.pw # unique identifier
    name: webmail.home31.pw
    description: 'Email server' # default=empty
    url: 'https://webmail.home31.pw/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: tv.home31.pw
    name: tv.home31.pw
    description: 'Stream Movies and TV'
    url: 'https://tv.home31.pw'
    method: GET
    expectStatus: 200
    followRedirect: true
    
  - id: ombi.home31.pw
    name: ombi.home31.pw
    description: 'Request new TV series and Movies'
    url: 'https://ombi.home31.pw/'
    method: GET
    expectStatus: 200
    
  - id: cloud.home31.pw
    name: cloud.home31.pw
    description: 'Cloud storage'
    url: 'https://cloud.home31.pw/'
    method: GET
    expectStatus: 200
    followRedirect: true
    
  - id: dash.home31.pw
    name: dash.home31.pw
    description: 'Dashboard'
    url: 'https://dash.home31.pw/'
    method: GET
    expectStatus: 200
    
  - id: pass.home31.pw
    name: pass.home31.pw
    description: 'Bitwarden password manager'
    url: 'https://pass.home31.pw/'
    method: GET
    expectStatus: 200

  - id: transfer.boixu.com
    name: transfer.boixu.com
    description: 'Simple encrypted file transfer'
    url: 'https://transfer.boixu.com/'
    method: GET
    expectStatus: 200
